### ISSUE TITLE
hi, i use the super_resolution.py, the result is below, does it look fine as expected?

### ISSUE THREAD

**Issue by leonardodora** [genforce/mganprior#1]
and it took a very long time per pic, could you please tell me how can i speed up?

![image](https://user-images.githubusercontent.com/13816743/78255862-6f9f2b80-752a-11ea-8e30-e27430249a1c.png)
![image](https://user-images.githubusercontent.com/13816743/78256224-d45a8600-752a-11ea-88bf-834757e89fd1.png)

**Comment by JasonGUTU** [comment]
Hi, 

For the image quality, it will be different if you run super-resolution multiple times as the initial value affects the final results. We use PGGAN in the released code. You can also change the `inversion_type` to StyleGAN-w+ to use StyleGAN, which will get better results.

To speed up, you can switch off the video generation by set `video` to False. Or you can make it parallel when running multiple images.

**Comment by leonardodora** [comment]
> Hi,
> 
> For the image quality, it will be different if you run super-resolution multiple times as the initial value affects the final results. We use PGGAN in the released code. You can also change the `inversion_type` to StyleGAN-w+ to use StyleGAN, which will get better results.
> 
> To speed up, you can switch off the video generation by set `video` to False. Or you can make it parallel when running multiple images.

thanks for your reply, I will try StyleGAN.
btw, can i just super-resolution 256-resolution images?  1024 is too big for me

**Comment by JasonGUTU** [comment]
Unfortunately not.  A feature of our work is the use of a pre-trained GAN network. The function and results are closely related to the GAN model you used. The PGGAN and StyleGAN are all designed to generate 1024-resolution images. So the output resolution is limited to be 1024. 

How to use GAN as a prior more flexible will be a good research topic.

**Comment by JasonGUTU** [comment]
> > Hi,
> > For the image quality, it will be different if you run super-resolution multiple times as the initial value affects the final results. We use PGGAN in the released code. You can also change the `inversion_type` to StyleGAN-w+ to use StyleGAN, which will get better results.
> > To speed up, you can switch off the video generation by set `video` to False. Or you can make it parallel when running multiple images.
> 
> thanks for your reply, I will try StyleGAN.
> btw, can i just super-resolution 256-resolution images? 1024 is too big for me

Unfortunately not. A feature of our work is the use of a pre-trained GAN network. The function and results are closely related to the GAN model you used. The PGGAN and StyleGAN are all designed to generate 1024-resolution images. So the output resolution is limited to be 1024.

How to use GAN as a prior more flexible will be a good research topic.

**Comment by leonardodora** [comment]
> > > Hi,
> > > For the image quality, it will be different if you run super-resolution multiple times as the initial value affects the final results. We use PGGAN in the released code. You can also change the `inversion_type` to StyleGAN-w+ to use StyleGAN, which will get better results.
> > > To speed up, you can switch off the video generation by set `video` to False. Or you can make it parallel when running multiple images.
> > 
> > 
> > thanks for your reply, I will try StyleGAN.
> > btw, can i just super-resolution 256-resolution images? 1024 is too big for me
> 
> Unfortunately not. A feature of our work is the use of a pre-trained GAN network. The function and results are closely related to the GAN model you used. The PGGAN and StyleGAN are all designed to generate 1024-resolution images. So the output resolution is limited to be 1024.
> 
> How to use GAN as a prior more flexible will be a good research topic.

got it!
so if i want to super-resolution 256-resolution images, i need to train my own 256-resolution stylegan,
is it correct?

**Comment by JasonGUTU** [comment]
> > Hi,
> > For the image quality, it will be different if you run super-resolution multiple times as the initial value affects the final results. We use PGGAN in the released code. You can also change the `inversion_type` to StyleGAN-w+ to use StyleGAN, which will get better results.
> > To speed up, you can switch off the video generation by set `video` to False. Or you can make it parallel when running multiple images.
> 
> thanks for your reply, I will try StyleGAN.
> btw, can i just super-resolution 256-resolution images? 1024 is too big for me

Another reminder, when you use StyleGAN, set `init_type` to zero lead to better results, while for PGGAN the `init_type` is Norm.

**Comment by huangzh13** [comment]
> > > Hi,
> > > For the image quality, it will be different if you run super-resolution multiple times as the initial value affects the final results. We use PGGAN in the released code. You can also change the `inversion_type` to StyleGAN-w+ to use StyleGAN, which will get better results.
> > > To speed up, you can switch off the video generation by set `video` to False. Or you can make it parallel when running multiple images.
> > 
> > 
> > thanks for your reply, I will try StyleGAN.
> > btw, can i just super-resolution 256-resolution images? 1024 is too big for me
> 
> Another reminder, when you use StyleGAN, set `init_type` to zero will lead to better results, while for PGGAN the `init_type` is Norm.

I noticed that in the released code, there are only `PGAN-Multi-Z`, but `StyleGAN-Multi-Z`. Is this because `stylegan-w +` has already achieved good enough results?

**Comment by JasonGUTU** [comment]
> > > > Hi,
> > > > For the image quality, it will be different if you run super-resolution multiple times as the initial value affects the final results. We use PGGAN in the released code. You can also change the `inversion_type` to StyleGAN-w+ to use StyleGAN, which will get better results.
> > > > To speed up, you can switch off the video generation by set `video` to False. Or you can make it parallel when running multiple images.
> > > 
> > > 
> > > thanks for your reply, I will try StyleGAN.
> > > btw, can i just super-resolution 256-resolution images? 1024 is too big for me
> > 
> > 
> > Another reminder, when you use StyleGAN, set `init_type` to zero will lead to better results, while for PGGAN the `init_type` is Norm.
> 
> I noticed that in the released code, there are only `PGAN-Multi-Z`, but `StyleGAN-Multi-Z`. Is this because `stylegan-w +` has already achieved good enough results?

Yes. And actually, to some extent, the `stylegan-w+` is equivalent to multi-code framework on stylegan  --  the w+ space naturally has multi-w to encode the image.

**Comment by laulampaul** [comment]
In super_resolution.py，the model address is models/pretrain/pytorch/pggan_celebahq1024_generator.pth, but I download from your link below PGGAN offical. The name is karras2018iclr-celebahq-1024x1024.pkl. How can I download the corrent pretrained model ?
