### ISSUE TITLE
About denoising

### ISSUE THREAD

**Issue by weiyichang** [genforce/mganprior#10]
Hi
Thanks for sharing this awesome work.
I am curious about how to use mganprior for the task of image denoising
(since there is no loss function described in paper, I have no idea about how to implement this feature) 
Is it similar to the task of image inpainting (we need the "mask" as input) ?
Or do you have other suggestions?
Thanks in advance !!!

**Comment by ShenYujun** [comment]
Yes, you are right. We need to know the position of noise in advance.

**Comment by weiyichang** [comment]
I see, and thanks for your quick response
