### ISSUE TITLE
details about image denoising

### ISSUE THREAD

**Issue by bingxumu** [genforce/mganprior#19]
Hi! Thanks for the great work!
This paper mentioned that mganprior can also be used for image denoising. But I'm not sure how to achieve it. Could you give me more details about image denoising? Like this
![image](https://user-images.githubusercontent.com/51730679/115350352-9557ab00-a1e7-11eb-94e5-f8442508dd18.png)
Thanks again for your great work!

**Comment by ShenYujun** [comment]
In practice, we assume that the noise mode / noise pattern is already known. In that case, we can only use the noise-free region to reconstruct the image. With the pre-trained GANs as prior, the noise-include region will be recovered automatically.

**Comment by bingxumu** [comment]
Is that means wo have the noise image and the "noise mask"  to be the input, like the inpainting mask?

**Comment by ShenYujun** [comment]
Yes, it requires to pre-know the noise model.

**Comment by bingxumu** [comment]
Got it! Thanks for your reply!
