### ISSUE TITLE
How to reconstruct a bedroom image using PGGAN trained on CelebA HQ?

### ISSUE THREAD

**Issue by hcwang95** [genforce/mganprior#6]
Would you mind sharing what is the procedure to do GAN inversion of bedroom image on PGGAN trained on face dataset (Fig.10 in the paper)? The size of the images are different between bedroom and face datasets.

Thanks a lot for the help!

**Comment by JasonGUTU** [comment]
Hi,

This approach may help: upsample the bedroom images to 1024x1024 with SR methods or even bicubic upsampling.

**Comment by hcwang95** [comment]
Got it. Thanks for the reply!
